kind: pipeline
name: default

steps:
- name: test
  image: node:latest
  commands:
  - npm install
  - npm run test 
  environment:
    GOPROXY: https://goproxy.cn # proxy.golang.org is blocked in China, this proxy is not
    GOSUMDB: sum.golang.org
  when:
    event:
    - pull_request
    - push
    
- name: build
  image: node:latest
  commands:
  - npm install
  when:
    event:
    - pull_request
    - push
  
