pipeline:
test:
    image: node:latest
    environment:
      - DEBUG=*
    commands:
      - npm install
      - npm run test   
  build:
    image: node:latest
    environment:
      - DEBUG=*
    commands:
      - npm install
